# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-20 19:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tour_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 20, 19, 33, 53, 983795, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tour',
            name='email',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
