# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-25 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pages', '0005_auto_20190320_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='number_of_tour',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
