# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-25 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pages', '0006_tour_number_of_tour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='number_of_tour',
            new_name='number_of_people',
        ),
    ]
