# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-27 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.TextField(max_length=300)),
                ('color', models.TextField(max_length=500)),
            ],
        ),
    ]
